# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton, QVBoxLayout, QMessageBox

from ools.PyQt5.QtWidgets import QDialog


class SecondForm(QWidget):
    def __init__(self, type=None):
        super().__init__()
        self.type = type
        self.path = None
        self.initUI()

    def initUI(self):
        self.setWindowTitle("Second Form")
        layout = QVBoxLayout()
        self.label1 = QLabel("Enter The Path:", self)
        layout.addWidget(self.label1)
        self.textBox1 = QLineEdit(self)
        layout.addWidget(self.textBox1)
        self.label2 = QLabel("Note: Size of image should be within 300x600", self)
        layout.addWidget(self.label2)
        self.button1 = QPushButton("OK", self)
        self.button1.clicked.connect(self.button1_click)
        layout.addWidget(self.button1)
        self.setLayout(layout)

    def button1_click(self):
        self.path = self.textBox1.text()
        if self.is_valid_path(self.path):
            self.close()
        else:
            self.show_error_message("Invalid path. Please enter a valid file path.")

    def is_valid_path(self, path):
       
        return os.path.isfile(path)

    def show_error_message(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText(message)
        msg.setWindowTitle("Error")
        msg.exec_()

    def get_path(self):
        return self.path

    def get_type(self):
        return self.type


def main():
    app = QApplication(sys.argv)
    form = SecondForm()
    if form.exec_() == QDialog.Accepted:
        print(f"Selected Path: {form.get_path()}")
    form.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
     app = QApplication(sys.argv)
     form = SecondForm()
     if form.exec_() == QDialog.Accepted:
        print(f"Selected Path: {form.get_path()}")
     form.show()
     sys.exit(app.exec_())
